import type { Competition } from "../types";

/**
 * football-data.org is the ONLY real data provider used by this app (API-Football support
 * still exists in providers/apiFootballProvider.ts but is intentionally disconnected — see
 * CLAUDE.md). `providerCompetitionCode` values below come straight from football-data.org's
 * own documented competition list; we never guess a code for a competition we haven't
 * confirmed against https://api.football-data.org/v4/competitions.
 *
 * "season" nas APIs de futebol nem sempre é o ano corrente: ligas de calendário europeu
 * (ago–mai) e a Champions League são rotuladas pelo ANO DE INÍCIO da temporada (ex.: a
 * temporada 2025-26 é `season=2025`, mesmo depois de virar 2026), enquanto ligas de
 * calendário anual (Brasileirão) e torneios de edição única (Copa do Mundo) usam o próprio
 * ano civil. Usar o valor errado faz a API real devolver uma temporada ainda sem jogos
 * (todos os times com 0 pontos) em vez de um erro — revisar a cada virada de temporada.
 */
const CALENDAR_YEAR_SEASON = 2026;
const EUROPEAN_SPLIT_SEASON = 2025;

/**
 * Competições confirmadas no catálogo público da football-data.org, priorizadas para o
 * Free Tier (plano "TIER_ONE"). O status real de acesso (available/unavailable_plan) é
 * recalculado em tempo real contra /v4/competitions em competitionAccess.ts — o `status`
 * aqui é só o valor-base assumido até essa verificação rodar.
 */
export const competitions: Competition[] = [
  {
    id: "premier-league",
    name: "Premier League",
    country: "Inglaterra",
    continent: "Europa",
    type: "league",
    provider: "football-data",
    providerCompetitionCode: "PL",
    season: EUROPEAN_SPLIT_SEASON,
    hasRelegation: true,
    relegationSpots: 3,
    qualificationSpots: 5,
    titleSpots: 1,
    status: "available",
  },
  {
    id: "championship-inglaterra",
    name: "Championship (Inglaterra)",
    country: "Inglaterra",
    continent: "Europa",
    type: "league",
    provider: "football-data",
    providerCompetitionCode: "ELC",
    season: EUROPEAN_SPLIT_SEASON,
    hasRelegation: true,
    relegationSpots: 3,
    qualificationSpots: 2,
    titleSpots: 1,
    status: "available",
  },
  {
    id: "la-liga",
    name: "La Liga",
    country: "Espanha",
    continent: "Europa",
    type: "league",
    provider: "football-data",
    providerCompetitionCode: "PD",
    season: EUROPEAN_SPLIT_SEASON,
    hasRelegation: true,
    relegationSpots: 3,
    qualificationSpots: 4,
    titleSpots: 1,
    status: "available",
  },
  {
    id: "serie-a-italia",
    name: "Serie A Itália",
    country: "Itália",
    continent: "Europa",
    type: "league",
    provider: "football-data",
    providerCompetitionCode: "SA",
    season: EUROPEAN_SPLIT_SEASON,
    hasRelegation: true,
    relegationSpots: 3,
    qualificationSpots: 4,
    titleSpots: 1,
    status: "available",
  },
  {
    id: "bundesliga",
    name: "Bundesliga",
    country: "Alemanha",
    continent: "Europa",
    type: "league",
    provider: "football-data",
    providerCompetitionCode: "BL1",
    season: EUROPEAN_SPLIT_SEASON,
    hasRelegation: true,
    relegationSpots: 2,
    qualificationSpots: 4,
    titleSpots: 1,
    status: "available",
  },
  {
    id: "ligue-1",
    name: "Ligue 1",
    country: "França",
    continent: "Europa",
    type: "league",
    provider: "football-data",
    providerCompetitionCode: "FL1",
    season: EUROPEAN_SPLIT_SEASON,
    hasRelegation: true,
    relegationSpots: 2,
    qualificationSpots: 4,
    titleSpots: 1,
    status: "available",
  },
  {
    id: "primeira-liga-portugal",
    name: "Primeira Liga",
    country: "Portugal",
    continent: "Europa",
    type: "league",
    provider: "football-data",
    providerCompetitionCode: "PPL",
    season: EUROPEAN_SPLIT_SEASON,
    hasRelegation: true,
    relegationSpots: 2,
    qualificationSpots: 3,
    titleSpots: 1,
    status: "available",
  },
  {
    id: "eredivisie",
    name: "Eredivisie",
    country: "Holanda",
    continent: "Europa",
    type: "league",
    provider: "football-data",
    providerCompetitionCode: "DED",
    season: EUROPEAN_SPLIT_SEASON,
    hasRelegation: true,
    relegationSpots: 2,
    qualificationSpots: 3,
    titleSpots: 1,
    status: "available",
  },
  {
    id: "champions-league",
    name: "UEFA Champions League",
    continent: "Europa",
    type: "groups",
    provider: "football-data",
    providerCompetitionCode: "CL",
    season: EUROPEAN_SPLIT_SEASON,
    hasRelegation: false,
    qualificationSpots: 8,
    titleSpots: 1,
    status: "available",
  },
  {
    id: "brasileirao-serie-a",
    name: "Brasileirão Série A",
    country: "Brasil",
    continent: "América do Sul",
    type: "league",
    provider: "football-data",
    providerCompetitionCode: "BSA",
    season: CALENDAR_YEAR_SEASON,
    hasRelegation: true,
    relegationSpots: 4,
    qualificationSpots: 6,
    titleSpots: 1,
    status: "available",
  },
  {
    // 2026 é a primeira edição com 48 seleções (12 grupos de 4; top 2 + 8 melhores
    // terceiros avançam à fase de 32). Ver worldCup.ts para o modo de exibição
    // (dados oficiais / só calendário / simulação) usado quando standings reais
    // ainda não estão completos na football-data.org.
    id: "copa-do-mundo",
    name: "Copa do Mundo FIFA",
    continent: "Global",
    type: "groups",
    provider: "football-data",
    providerCompetitionCode: "WC",
    season: CALENDAR_YEAR_SEASON,
    hasRelegation: false,
    qualificationSpots: 32,
    titleSpots: 1,
    status: "available",
  },
  {
    id: "eurocopa",
    name: "Eurocopa",
    continent: "Europa",
    type: "groups",
    provider: "football-data",
    providerCompetitionCode: "EC",
    season: CALENDAR_YEAR_SEASON,
    hasRelegation: false,
    status: "available",
  },

  // ---- Secundárias: mantidas no registry para referência/busca futura, mas sem código
  // confirmado no catálogo da football-data.org. Ficam fora da listagem principal da
  // home ("Outras competições em análise") até alguém validar o código real. ----
  {
    id: "brasileirao-serie-b",
    name: "Brasileirão Série B",
    country: "Brasil",
    continent: "América do Sul",
    type: "league",
    provider: "football-data",
    season: CALENDAR_YEAR_SEASON,
    hasRelegation: true,
    relegationSpots: 4,
    qualificationSpots: 4,
    titleSpots: 1,
    status: "needs_mapping",
  },
  {
    id: "copa-do-brasil",
    name: "Copa do Brasil",
    country: "Brasil",
    continent: "América do Sul",
    type: "cup",
    provider: "football-data",
    season: CALENDAR_YEAR_SEASON,
    hasRelegation: false,
    status: "needs_mapping",
  },
  {
    id: "libertadores",
    name: "Copa Conmebol Libertadores",
    continent: "América do Sul",
    type: "groups",
    provider: "football-data",
    season: CALENDAR_YEAR_SEASON,
    hasRelegation: false,
    qualificationSpots: 8,
    titleSpots: 1,
    status: "needs_mapping",
  },
  {
    id: "copa-america",
    name: "Copa América",
    continent: "América do Sul",
    type: "groups",
    provider: "football-data",
    season: CALENDAR_YEAR_SEASON,
    hasRelegation: false,
    status: "needs_mapping",
  },
  {
    id: "mundial-de-clubes",
    name: "Mundial de Clubes FIFA",
    continent: "Global",
    type: "knockout",
    provider: "football-data",
    season: CALENDAR_YEAR_SEASON,
    hasRelegation: false,
    status: "needs_mapping",
  },
  {
    id: "copa-sudamericana",
    name: "Copa Sudamericana",
    continent: "América do Sul",
    type: "groups",
    provider: "football-data",
    season: CALENDAR_YEAR_SEASON,
    hasRelegation: false,
    status: "needs_mapping",
  },
  {
    id: "mls",
    name: "MLS",
    country: "Estados Unidos",
    continent: "América do Norte",
    type: "league",
    provider: "football-data",
    season: CALENDAR_YEAR_SEASON,
    hasRelegation: false,
    status: "needs_mapping",
  },
  {
    id: "segunda-division-espanha",
    name: "Segunda División",
    country: "Espanha",
    continent: "Europa",
    type: "league",
    provider: "football-data",
    season: EUROPEAN_SPLIT_SEASON,
    hasRelegation: true,
    status: "needs_mapping",
  },
  {
    id: "serie-b-italia",
    name: "Serie B Itália",
    country: "Itália",
    continent: "Europa",
    type: "league",
    provider: "football-data",
    season: EUROPEAN_SPLIT_SEASON,
    hasRelegation: true,
    status: "needs_mapping",
  },
  {
    id: "ligue-2",
    name: "Ligue 2",
    country: "França",
    continent: "Europa",
    type: "league",
    provider: "football-data",
    season: EUROPEAN_SPLIT_SEASON,
    hasRelegation: true,
    status: "needs_mapping",
  },
  {
    id: "segunda-bundesliga",
    name: "2. Bundesliga",
    country: "Alemanha",
    continent: "Europa",
    type: "league",
    provider: "football-data",
    season: EUROPEAN_SPLIT_SEASON,
    hasRelegation: true,
    status: "needs_mapping",
  },
  {
    id: "dfb-pokal",
    name: "DFB-Pokal",
    country: "Alemanha",
    continent: "Europa",
    type: "cup",
    provider: "football-data",
    season: EUROPEAN_SPLIT_SEASON,
    hasRelegation: false,
    status: "needs_mapping",
  },
  {
    id: "fa-cup",
    name: "FA Cup",
    country: "Inglaterra",
    continent: "Europa",
    type: "cup",
    provider: "football-data",
    season: EUROPEAN_SPLIT_SEASON,
    hasRelegation: false,
    status: "needs_mapping",
  },
  {
    id: "copa-del-rey",
    name: "Copa del Rey",
    country: "Espanha",
    continent: "Europa",
    type: "cup",
    provider: "football-data",
    season: EUROPEAN_SPLIT_SEASON,
    hasRelegation: false,
    status: "needs_mapping",
  },
  {
    id: "coppa-italia",
    name: "Coppa Italia",
    country: "Itália",
    continent: "Europa",
    type: "cup",
    provider: "football-data",
    season: EUROPEAN_SPLIT_SEASON,
    hasRelegation: false,
    status: "needs_mapping",
  },
];

export function getCompetitionById(id: string): Competition | undefined {
  return competitions.find((competition) => competition.id === id);
}

export function isCompetitionMapped(competition: Competition): boolean {
  if (competition.status === "needs_mapping") return false;
  return Boolean(competition.providerCompetitionCode);
}

export function listCompetitions(): Competition[] {
  return competitions;
}
